//
//  FUConstHeader.h
//  ForU
//
//  Created by 孙昕 on 15/2/11.
//  Copyright (c) 2015年 孙昕. All rights reserved.
//

#ifndef ForU_FUConstHeader_h
#define ForU_FUConstHeader_h
#define MSGPHYSICALCHANGE @"MsgPhysicalChange"
#define MSGMONEYCHANGE @"MsgMoneyChange"
#define MSGIOICHANGE @"MsgIOIChange"
#define MSGMOODCHANGE @"MsgMoodChange"
enum GIRLTYPE {LOLI,MAID,QUEEN};
enum PERSONTYPE {PLAYER,GIRL};
enum NOTIFYTYPE {CALL,DATEITEMEND,WORKHELPEND,WORKIOI,WORKMEET,WORKHELP,LEISUREIOI,LEISUREDATE,WORKEVENT,LEISUREEVENT,NONE};
enum DATETYPE {EAT,FILM,WALK,PARK};
enum PLAYERSTATE {LEISURE,SLEEP,WORK};
enum ACTIONEYETYPE {LOOKFACE,GAZEFACE,LOOKBREAST,GAZEBREAST};
enum ACTIONBODYTYPE {PATSHOULDER,TOUCHHAIR,TOUCHHAND,KNEADFACE,HUG,KISS,MASSAGE,FINGERWAR,HUGWAIST,RUBNOSE,HANDINHAND,LIFT};
#endif








